name: Node CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.20.8
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
